// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcWaWiv_PUCvoHB-jSm_Ya6uhL1VgsXUA',
    appId: '1:270441798341:web:f76d66ed85426f2d016eac',
    messagingSenderId: '270441798341',
    projectId: 'shopease-ecommearc-app',
    authDomain: 'shopease-ecommearc-app.firebaseapp.com',
    storageBucket: 'shopease-ecommearc-app.firebasestorage.app',
    measurementId: 'G-RDEWK852NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXni5_dNLDFpZoOY36v8DscKQQts2ZZio',
    appId: '1:270441798341:android:a84185d116558739016eac',
    messagingSenderId: '270441798341',
    projectId: 'shopease-ecommearc-app',
    storageBucket: 'shopease-ecommearc-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkBH7zFP2JnI0vSR96mN9fyUdDrIkCeE0',
    appId: '1:270441798341:ios:90d7c523991f6eaf016eac',
    messagingSenderId: '270441798341',
    projectId: 'shopease-ecommearc-app',
    storageBucket: 'shopease-ecommearc-app.firebasestorage.app',
    iosBundleId: 'com.example.shopeaseEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkBH7zFP2JnI0vSR96mN9fyUdDrIkCeE0',
    appId: '1:270441798341:ios:90d7c523991f6eaf016eac',
    messagingSenderId: '270441798341',
    projectId: 'shopease-ecommearc-app',
    storageBucket: 'shopease-ecommearc-app.firebasestorage.app',
    iosBundleId: 'com.example.shopeaseEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcWaWiv_PUCvoHB-jSm_Ya6uhL1VgsXUA',
    appId: '1:270441798341:web:debbbcc9aa2d82b3016eac',
    messagingSenderId: '270441798341',
    projectId: 'shopease-ecommearc-app',
    authDomain: 'shopease-ecommearc-app.firebaseapp.com',
    storageBucket: 'shopease-ecommearc-app.firebasestorage.app',
    measurementId: 'G-N4SNNEN6W4',
  );
}
